# Apa Adanya - Realism rebuild. Folder edition.
clouds=off
sun=false
moon=false
oldLighting=false
underwaterOverlay=false
vignette=false
separateAo=true
shadowTranslucent=false
shadowEntities=true
shadowBlockEntities=true
rain.depth=false
particles.ordering=mixed
screen=<empty> <profile> <empty> [LIGHTING] [WATER] [SKY] [SHADOWS] [POST] [MATERIALS]
screen.columns=2
screen.LIGHTING=SSAO SSGI GI_SAMPLES GI_STRENGTH NIGHT_BRIGHTNESS VOLUMETRIC_LIGHT FOG_DENSITY
screen.WATER=SSR SSR_STEPS WATER_WAVES WATER_CLARITY WATER_ROUGHNESS
screen.SKY=CLOUD_SHADOWS VOLUMETRIC_CLOUDS FAST_CLOUDS CLOUD_STEPS CLOUD_COVERAGE
screen.SHADOWS=SHADOWS shadowMapResolution shadowDistance SHADOW_SAMPLES SHADOW_ALPHA_TEST
screen.POST=COLOR_CONTRAST COLOR_SATURATION EXPOSURE BLOOM BLOOM_STRENGTH FXAA
screen.MATERIALS=WAVING_FOLIAGE RESOURCE_NORMALS
sliders=COLOR_CONTRAST COLOR_SATURATION WATER_ROUGHNESS NIGHT_BRIGHTNESS EXPOSURE BLOOM_STRENGTH GI_STRENGTH WATER_WAVES WATER_CLARITY CLOUD_COVERAGE FOG_DENSITY
profile.POTATO=!SHADOWS !SSAO !SSR !SSGI !VOLUMETRIC_CLOUDS !FAST_CLOUDS !VOLUMETRIC_LIGHT !BLOOM !FXAA !WAVING_FOLIAGE !CLOUD_SHADOWS !SHADOW_ALPHA_TEST SHADOW_SAMPLES:2 shadowMapResolution:512 shadowDistance:80.0
profile.LOW=SHADOWS !SSAO !SSR !SSGI !VOLUMETRIC_CLOUDS FAST_CLOUDS !VOLUMETRIC_LIGHT !BLOOM FXAA !WAVING_FOLIAGE !CLOUD_SHADOWS !SHADOW_ALPHA_TEST SHADOW_SAMPLES:2 shadowMapResolution:1024 shadowDistance:96.0
profile.MEDIUM=SHADOWS SSAO SSR !SSGI VOLUMETRIC_CLOUDS !FAST_CLOUDS !VOLUMETRIC_LIGHT BLOOM FXAA WAVING_FOLIAGE CLOUD_SHADOWS SHADOW_ALPHA_TEST SSR_STEPS:18 CLOUD_STEPS:12 SHADOW_SAMPLES:4 shadowMapResolution:1024 shadowDistance:144.0
profile.HIGH=SHADOWS SSAO SSR SSGI VOLUMETRIC_CLOUDS !FAST_CLOUDS VOLUMETRIC_LIGHT BLOOM FXAA WAVING_FOLIAGE CLOUD_SHADOWS SHADOW_ALPHA_TEST SSR_STEPS:32 GI_SAMPLES:3 CLOUD_STEPS:16 SHADOW_SAMPLES:6 shadowMapResolution:2048 shadowDistance:176.0
profile.ULTRA=SHADOWS SSAO SSR SSGI VOLUMETRIC_CLOUDS !FAST_CLOUDS VOLUMETRIC_LIGHT BLOOM FXAA WAVING_FOLIAGE CLOUD_SHADOWS SHADOW_ALPHA_TEST SSR_STEPS:48 GI_SAMPLES:6 CLOUD_STEPS:24 SHADOW_SAMPLES:12 shadowMapResolution:2048 shadowDistance:224.0
size.buffer.colortex4=0.25 0.25
size.buffer.colortex5=0.25 0.25
blend.gbuffers_terrain=off
blend.gbuffers_water.colortex1=off
blend.gbuffers_water.colortex2=off
blend.gbuffers_entities.colortex1=off
blend.gbuffers_entities.colortex2=off
blend.gbuffers_hand.colortex1=off
blend.gbuffers_hand.colortex2=off
blend.dh_terrain=off
blend.dh_water.colortex1=off
blend.dh_water.colortex2=off
dhShadow.enabled=false
size.buffer.colortex7=128 64
size.buffer.colortex8=128 128

