# Apa Adanya - Realism rebuild. Folder edition.
clouds=off
sun=false
moon=false
oldLighting=false
underwaterOverlay=false
vignette=false
separateAo=true
shadowTranslucent=false
shadowEntities=true
shadowBlockEntities=true
rain.depth=false
particles.ordering=mixed
screen=<profile> [LIGHTING] [WATER] [SKY] [SHADOWS] [POST] [MATERIALS]
screen.columns=2
screen.LIGHTING=SSGI GI_SAMPLES GI_STRENGTH NIGHT_BRIGHTNESS VOLUMETRIC_LIGHT FOG_DENSITY
screen.WATER=SSR SSR_STEPS WATER_WAVES WATER_CLARITY WATER_ROUGHNESS
screen.SKY=CLOUD_SHADOWS VOLUMETRIC_CLOUDS CLOUD_STEPS CLOUD_COVERAGE
screen.SHADOWS=shadowMapResolution shadowDistance SHADOW_SAMPLES
screen.POST=COLOR_CONTRAST COLOR_SATURATION EXPOSURE BLOOM BLOOM_STRENGTH FXAA
screen.MATERIALS=WAVING_FOLIAGE RESOURCE_NORMALS
sliders=COLOR_CONTRAST COLOR_SATURATION WATER_ROUGHNESS NIGHT_BRIGHTNESS EXPOSURE BLOOM_STRENGTH GI_STRENGTH WATER_WAVES WATER_CLARITY CLOUD_COVERAGE FOG_DENSITY
profile.BALANCED=SSR !SSGI VOLUMETRIC_CLOUDS !VOLUMETRIC_LIGHT BLOOM FXAA SSR_STEPS:24 GI_SAMPLES:2 CLOUD_STEPS:12 SHADOW_SAMPLES:4 shadowMapResolution:2048 shadowDistance:120.0
profile.HIGH=SSR SSGI VOLUMETRIC_CLOUDS VOLUMETRIC_LIGHT BLOOM FXAA SSR_STEPS:48 GI_SAMPLES:4 CLOUD_STEPS:20 SHADOW_SAMPLES:12 shadowMapResolution:2048 shadowDistance:160.0
profile.ULTRA=SSR SSGI VOLUMETRIC_CLOUDS VOLUMETRIC_LIGHT BLOOM FXAA SSR_STEPS:96 GI_SAMPLES:8 CLOUD_STEPS:36 SHADOW_SAMPLES:16 shadowMapResolution:4096 shadowDistance:224.0
size.buffer.colortex4=0.25 0.25
size.buffer.colortex5=0.25 0.25
blend.gbuffers_terrain=off
blend.gbuffers_water.colortex1=off
blend.gbuffers_water.colortex2=off
blend.gbuffers_entities.colortex1=off
blend.gbuffers_entities.colortex2=off
blend.gbuffers_hand.colortex1=off
blend.gbuffers_hand.colortex2=off
blend.dh_terrain=off
blend.dh_water.colortex1=off
blend.dh_water.colortex2=off
dhShadow.enabled=false
size.buffer.colortex7=1024 512


size.buffer.colortex8=256 256

